version: '1.1'
services:
  app-php:
    container_name: app-php
    volumes:
      - .:/var/www/html
    build: 
      context: .
      dockerfile: ./.docker/Dockerfile
    ports:
      - 8080:80
      - 8081:8081
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    command: bash -c "composer install --ignore-platform-req=ext-gd && apache2-foreground"
    networks:
      - app-network
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql
    container_name: mysqldb
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: toursexplorer
      MYSQL_ROOT_PASSWORD: root
    command: --default-authentication-plugin=mysql_native_password
      
    networks:
      - app-network
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadminTourExplorer
    environment:
      PMA_HOST: mysqldb
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8082:80
    volumes:
      - ./.docker/phpmyadmin:/sessions
networks:
  app-network:
    driver: bridge