version: '1.1'
services:
  app-php:
    container_name: app-php
    volumes:
      - .:/var/www/html
    build: 
      context: .
      dockerfile: ./.docker/Dockerfile
    ports:
      - 8080:80
      - 8081:8081
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    command: bash -c "composer install --ignore-platform-req=ext-gd && apache2-foreground && php -S app-php:8081"
    networks:
      - app-network
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql
    container_name: mysqldb
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: toursexplorer
      MYSQL_ROOT_PASSWORD: root
      # use caching sha2 password plugin
    command: --default-authentication-plugin=mysql_native_password
      
    networks:
      - app-network
    ports:
      - 3306:3306
networks:
  app-network:
    driver: bridge