version: '3'
services:
  php-app:
    container_name: tourExplorerSV
    build:
      context: ./
      dockerfile: .docker/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
      
    command: bash -c "composer install --ignore-platform-req=ext-gd && apache2-foreground"